# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195XV7hiY3-ZXRdsDocZSS3wmXy34ndLk
"""

a = int(input())
b = int(input())
s=a+b
d=a-b
p=a*b
print(s)
print(d)
print(p)