# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195XV7hiY3-ZXRdsDocZSS3wmXy34ndLk
"""

a = int(input())
    b = int(input())
    i=a//b
    f=float(a/b)
    print(i)
    print(f)